# Generated by Django 3.2.16 on 2023-01-07 02:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guest',
            field=models.CharField(default=api.models.generate_unique_code, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='guest_choice',
            field=models.CharField(default=api.models.generate_unique_code, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='host_choice',
            field=models.CharField(default=api.models.generate_unique_code, max_length=50),
        ),
    ]
