# Generated by Django 3.2.16 on 2023-01-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230107_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='host_score',
            field=models.IntegerField(default=0),
        ),
    ]
